#!/bin/bash -e

command -v cloc >/dev/null 2>&1 || { echo "Install cloc with: brew install cloc" >&2; exit 1; }

COUNT=$(cloc --exclude-dir=Carthage,build --include-lang=Swift,Kotlin .)

if [ "x$1" == "xnumber" ]
then
  echo "$COUNT" | grep SUM | awk '{print $5}'
else
  echo "$COUNT"
fi
