name: ReactiveAPI
options:
  bundleIdPrefix: it.sky
  deploymentTarget:
    iOS: "12.4"
settings:
    VALIDATE_WORKSPACE: YES
targets:
  ReactiveAPI:
    templates:
      - iOSFramework
    sources:
      - path: Sources/ReactiveAPI
    scheme:
      testTargets:
        - ReactiveAPI-Tests
  ReactiveAPIExt:
    templates:
      - iOSFramework
    sources:
      - path: Sources/ReactiveAPIExt
    scheme:
      testTargets:
        - ReactiveAPIExt-Tests
  ReactiveAPI-Tests:
    templates:
      - iOSTestFramework
    sources:
      - Tests/ReactiveAPITests
    dependencies:
      - target: ReactiveAPI
  ReactiveAPIExt-Tests:
    templates:
      - iOSTestFramework
    sources:
      - Tests/ReactiveAPIExtTests
    dependencies:
      - target: ReactiveAPIExt
targetTemplates:
  iOSFramework:
    platform: iOS
    type: framework
    info:
      path: ${target_name}.plist
      properties:
        CFBundleIdentifier: it.sky.${target_name}
        CFBundleShortVersionString: "1.13.0"
    sources:
      - path: Sources/ReactiveAPI
    scheme:
      gatherCoverageData: true
    dependencies:
      - carthage: RxSwift
  iOSFramework:
    platform: iOS
    type: framework
    info:
      path: ${target_name}.plist
      properties:
        CFBundleIdentifier: it.sky.${target_name}
        CFBundleShortVersionString: "1.13.0"
    sources:
      - path: Sources/ReactiveAPIExt
    scheme:
      gatherCoverageData: true
    dependencies:
      - carthage: RxSwift
  iOSTestFramework:
    type: bundle.unit-test
    platform: iOS
    scheme: {}
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: RxTest
      - carthage: RxBlocking
      - carthage: OHHTTPStubs
      - carthage: Swifter
