#!/bin/bash -e
VERSION=$(cat project.yml | grep CFBundleShortVersionString | awk '{print $2}' | head -n 1 | sed 's/"//g')
echo "Creating version: $VERSION"
git clean -fxd
xcodegen generate
./wcarthage bootstrap --platform iOS --cache-builds
./wcarthage build --archive --platform iOS --cache-builds
./wcarthage bootstrap --platform iOS
./wcarthage build --archive
hub release create -a ReactiveAPI.framework.zip -m "$VERSION" "$VERSION"
