import Foundation
import ReactiveAPI
import RxSwift

// this can be fully autogenerated with swagger codegen
public class AuthAPI: JSONReactiveAPI {

    public func login(username: String, password: String) -> Single<TokenPair> {
        return request(.post, url: absoluteURL("login"), bodyParams: [
            "username": username,
            "password": password
            ])
    }

    public func invalidate() -> Single<Void> {
        return request(url: absoluteURL("invalidate"))
    }

    public func renewToken(tokenPair: TokenPair?) -> Single<TokenPair> {
        return request(.post, url: absoluteURL("renewToken"), body: tokenPair)
    }

}
