import Foundation
import ReactiveAPI
import RxSwift

// this can be fully autogenerated with swagger codegen
class BackendAPI: JSONReactiveAPI {

    public func getVersion() -> Single<Version> {
        return request(url: absoluteURL("version"))
    }

}
